### ISSUE TITLE
java.lang.IllegalArgumentException: Unable to resolve classname: bigint

### ISSUE THREAD

**Issue by rap1ds** [clojurewerkz/money#34]
Steps to reproduce:

```
> clj -Sdeps '{:deps {clojurewerkz/money {:mvn/version "1.11.0"}}}'
Clojure 1.11.1
user=> (require '[clojurewerkz.money.amounts :as ams])
nil
user=> (defn positive? [m] (< (ams/minor-of m) 0))
Syntax error (IllegalArgumentException) compiling . at (REPL:1:21).
Unable to resolve classname: bigint
```

Please note that this doesn't happen in 1.10.0

```
> clj -Sdeps '{:deps {clojurewerkz/money {:mvn/version "1.10.0"}}}'
Clojure 1.11.1
user=> (require '[clojurewerkz.money.amounts :as ams])
WARNING: abs already refers to: #'clojure.core/abs in namespace: clojurewerkz.money.amounts, being replaced by: #'clojurewerkz.money.amounts/abs
nil
user=> (defn positive? [m] (< (ams/minor-of m) 0))
#'user/positive?
```

I believe the issue was introduced in PR #30 . The `:tag` value `bigint` is not one of the type hint aliases: https://clojure.org/reference/java_interop#TypeAliases

**Comment by michaelklishin** [comment]
Please submit a PR?On 21 Jun 2023, at 15:03, Mikko Koski ***@***.***> wrote:﻿
Steps to reproduce:
> clj -Sdeps '{:deps {clojurewerkz/money {:mvn/version "1.11.0"}}}'
Clojure 1.11.1
user=> (require '[clojurewerkz.money.amounts :as ams])
nil
user=> (defn positive? [m] (< (ams/minor-of m) 0))
Syntax error (IllegalArgumentException) compiling . at (REPL:1:21).
Unable to resolve classname: bigint

Please note that this doesn't happen in 1.10.0
> clj -Sdeps '{:deps {clojurewerkz/money {:mvn/version "1.10.0"}}}'
Clojure 1.11.1
user=> (require '[clojurewerkz.money.amounts :as ams])
WARNING: abs already refers to: #'clojure.core/abs in namespace: clojurewerkz.money.amounts, being replaced by: #'clojurewerkz.money.amounts/abs
nil
user=> (defn positive? [m] (< (ams/minor-of m) 0))
#'user/positive?

I believe the issue was introduced in PR #30 . The :tag value bigint is not one of the type hint aliases: https://clojure.org/reference/java_interop#TypeAliases
